import Head from "next/head";
import Image from "next/image";

import Hero from "./components/Hero";
import About from "./components/About";
import FeaturedBlogPosts from "./components/FeaturedBlogPosts";

export default function Home() {
  return (
    <main className="min-h-screen bg-[url('/assets/bg.png')] text-white flex flex-col">
      <Head>
        <title>Jossif Elefteriadis | Web3 Native</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <section className="flex flex-col lg:flex-row items-center">
        <About />
        <FeaturedBlogPosts />
      </section>
    </main>
  );
}
