import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <main className="min-h-screen bg-[url('./assets/bg.png')] flex flex-col items-center justify-between">
      <Head>
        <title>Jossif Elefteriadis | Web3 Native</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </main>
  );
}
