import Head from "next/head";
import Image from "next/image";

import Hero from "./components/Hero";

export default function Home() {
  return (
    <main className="bg-[url('/assets/bg.png')] text-white flex flex-col justify-between items-center">
      <Head>
        <title>Jossif Elefteriadis | Web3 Native</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </main>
  );
}
