import Head from "next/head";
// import Link from "next/link";

import Nav from "../components/nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jossif Elefteriadis | Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </div>
  );
}
